name: receipt_recognition
description: "A Flutter package for scanning and extracting structured data from supermarket receipts using Google's ML Kit."
version: 0.2.1
homepage: https://github.com/manfredbork/receipt_recognition
repository: https://github.com/manfredbork/receipt_recognition

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  unorm_dart: ^0.3.0
  fuzzywuzzy: ^1.2.0
  google_mlkit_text_recognition: ^0.15.0
  intl: ^0.20.2
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.2
  flutter_lints: ^6.0.0
  mockito: ^5.0.17
  build_runner: ^2.1.7
  google_mlkit_commons: ^0.11.0
